// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cache.sql

package dbgen

import (
	"context"
)

const getCachedTranslation = `-- name: GetCachedTranslation :one
SELECT translated FROM translation_cache WHERE hash = $1
`

func (q *Queries) GetCachedTranslation(ctx context.Context, hash string) (string, error) {
	row := q.db.QueryRow(ctx, getCachedTranslation, hash)
	var translated string
	err := row.Scan(&translated)
	return translated, err
}

const listAllCachedTranslations = `-- name: ListAllCachedTranslations :many
SELECT hash, translated FROM translation_cache
`

type ListAllCachedTranslationsRow struct {
	Hash       string `json:"hash"`
	Translated string `json:"translated"`
}

func (q *Queries) ListAllCachedTranslations(ctx context.Context) ([]ListAllCachedTranslationsRow, error) {
	rows, err := q.db.Query(ctx, listAllCachedTranslations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCachedTranslationsRow{}
	for rows.Next() {
		var i ListAllCachedTranslationsRow
		if err := rows.Scan(&i.Hash, &i.Translated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCachedTranslation = `-- name: UpsertCachedTranslation :exec
INSERT INTO translation_cache (hash, source, translated)
VALUES ($1, $2, $3)
ON CONFLICT (hash) DO UPDATE SET translated = EXCLUDED.translated
`

type UpsertCachedTranslationParams struct {
	Hash       string `json:"hash"`
	Source     string `json:"source"`
	Translated string `json:"translated"`
}

func (q *Queries) UpsertCachedTranslation(ctx context.Context, arg UpsertCachedTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertCachedTranslation, arg.Hash, arg.Source, arg.Translated)
	return err
}
