// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embeddings.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const getEmbeddingByHash = `-- name: GetEmbeddingByHash :one
SELECT id, hash, source, context, file_path, created_at
FROM embeddings
WHERE hash = $1
`

type GetEmbeddingByHashRow struct {
	ID        int32              `json:"id"`
	Hash      string             `json:"hash"`
	Source    string             `json:"source"`
	Context   string             `json:"context"`
	FilePath  string             `json:"file_path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEmbeddingByHash(ctx context.Context, hash string) (GetEmbeddingByHashRow, error) {
	row := q.db.QueryRow(ctx, getEmbeddingByHash, hash)
	var i GetEmbeddingByHashRow
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Source,
		&i.Context,
		&i.FilePath,
		&i.CreatedAt,
	)
	return i, err
}

const insertEmbeddingWithVector = `-- name: InsertEmbeddingWithVector :exec
INSERT INTO embeddings (hash, source, context, file_path, embedding)
VALUES ($1, $2, $3, $4, $5::vector)
ON CONFLICT (hash) DO NOTHING
`

type InsertEmbeddingWithVectorParams struct {
	Hash     string          `json:"hash"`
	Source   string          `json:"source"`
	Context  string          `json:"context"`
	FilePath string          `json:"file_path"`
	Column5  pgvector.Vector `json:"column_5"`
}

func (q *Queries) InsertEmbeddingWithVector(ctx context.Context, arg InsertEmbeddingWithVectorParams) error {
	_, err := q.db.Exec(ctx, insertEmbeddingWithVector,
		arg.Hash,
		arg.Source,
		arg.Context,
		arg.FilePath,
		arg.Column5,
	)
	return err
}

const searchSimilarEmbeddings = `-- name: SearchSimilarEmbeddings :many
SELECT source, context, (1 - (embedding <=> $1::vector))::float8 AS similarity
FROM embeddings
WHERE embedding IS NOT NULL
ORDER BY embedding <=> $1::vector
LIMIT $2
`

type SearchSimilarEmbeddingsParams struct {
	Column1 pgvector.Vector `json:"column_1"`
	Limit   int32           `json:"limit"`
}

type SearchSimilarEmbeddingsRow struct {
	Source     string  `json:"source"`
	Context    string  `json:"context"`
	Similarity float64 `json:"similarity"`
}

func (q *Queries) SearchSimilarEmbeddings(ctx context.Context, arg SearchSimilarEmbeddingsParams) ([]SearchSimilarEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarEmbeddings, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSimilarEmbeddingsRow{}
	for rows.Next() {
		var i SearchSimilarEmbeddingsRow
		if err := rows.Scan(&i.Source, &i.Context, &i.Similarity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
