// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type Embedding struct {
	ID        int32              `json:"id"`
	Hash      string             `json:"hash"`
	Source    string             `json:"source"`
	Context   string             `json:"context"`
	FilePath  string             `json:"file_path"`
	Embedding pgvector_go.Vector `json:"embedding"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SeedTranslation struct {
	Hash           string             `json:"hash"`
	SourceText     string             `json:"source_text"`
	TranslatedText string             `json:"translated_text"`
	File           string             `json:"file"`
	FunctionName   string             `json:"function_name"`
	EntityType     string             `json:"entity_type"`
	IsSeed         bool               `json:"is_seed"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TranslationCache struct {
	Hash       string             `json:"hash"`
	Source     string             `json:"source"`
	Translated string             `json:"translated"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
